const skills = [
    "React JS",
    "NextJs",
    "JavaScript",
    "REST APIs",
    "JSON",
    "Redux",
    "React Hook Form",
    "Git/Github",
    "UI Design",
    "Component Libraries",
    "Firebase",
    "TypeScript",
    "SASS",
    "English",
    "Español",
    "HTML5/CSS",
    "Styled Components",
    "Vercel",
    "APIs",
    "Jest",
    "React Testing Library",
    "AntDesign",
    "Bootstrap",
    "Postman",
    "Axios",
    "Redux ToolKit",
    "Vite",
    "SWR",
    "Tailwind",
    "React Bootstrap",
];

export default skills;
